export const listings = [
  {
    image: '../src/assets/card-img.jpg',
    title: 'Cozy Cabin in the Woods',
    type: 'Entire home',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 120,
    rating: 4.8,
  },
  {
    image: '../src/assets/card-img.jpg',
    title: 'Cozy Cabin in the Woods',
    type: 'Entire home',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 120,
    rating: 4.8,
  },
  {
    image: '../src/assets/card-img.jpg',
    title: 'Cozy Cabin in the Woods',
    type: 'Entire home',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 120,
    rating: 4.8,
  },
  {
    image: '../src/assets/card-img.jpg',
    title: 'Cozy Cabin in the Woods',
    type: 'Entire home',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 120,
    rating: 4.8,
  },
  {
    image: '../src/assets/card-img.jpg',
    title: 'Cozy Cabin in the Woods',
    type: 'Entire home',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 120,
    rating: 4.8,
  },
  {
    image: '../src/assets/card-img.jpg',
    title: 'Cozy Cabin in the Woods',
    type: 'Entire home',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 120,
    rating: 4.8,
  },
  {
    image: '../src/assets/card-img.jpg',
    title: 'Cozy Cabin in the Woods',
    type: 'Entire home',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 120,
    rating: 4.8,
  },
  {
    image: '../src/assets/card-img.jpg',
    title: 'Cozy Cabin in the Woods',
    type: 'Entire home',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 120,
    rating: 4.8,
  },
  {
    image: '../src/assets/card-img.jpg',
    title: 'Cozy Cabin in the Woods',
    type: 'Entire home',
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    price: 120,
    rating: 4.8,
  }
    // Add more listings as needed
  ];
  